"""This file was auto-generated by scripts/agentscope_native_contract.py."""

POLICY_SHA256 = "fd895474da0566c72eb118bb9990dcb40804de3a960a94c0cf55edc6814ca255"
ALLOWED_RUNTIME_OPERATIONS: tuple[tuple[str, str], ...] = (
    ("DELETE", "/agent/{agent_id}"),
    ("DELETE", "/sessions/{session_id}"),
    ("GET", "/agent/"),
    ("GET", "/agent/schema/v2"),
    ("GET", "/health"),
    ("GET", "/sessions/"),
    ("GET", "/sessions/{session_id}/messages"),
    ("GET", "/sessions/{session_id}/status"),
    ("GET", "/sessions/{session_id}/stream"),
    ("GET", "/workspace/mcp"),
    ("GET", "/workspace/skill"),
    ("GET", "/workspace/status"),
    ("PATCH", "/sessions/{session_id}"),
    ("POST", "/agent/"),
    ("POST", "/chat/"),
    ("POST", "/sessions/"),
    ("POST", "/sessions/{session_id}/interrupt"),
)
