#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from check_docs_governance import collect_docs_governance_issues
from check_orphan_tests import collect_orphan_issues
from codex_governance_json import (
    annotation_contains_name,
    is_allowed_jsonobject_field,
    is_legacy_json_type_import,
    is_records_path,
    is_store_path,
    jsonobject_boundary_issue_specs,
    legacy_json_type_import_issue_specs,
)
from codex_governance_legacy_feedback import (
    legacy_feedback_active_ref_issue_specs,
    legacy_feedback_active_refs,
    legacy_feedback_repo_refs,
)
from codex_governance_typed_output import (
    annotation_contains_output_formatter_result_basemodel,
    annotation_is_bare_basemodel,
    annotation_is_base_json_union,
    is_typed_output_completion_function,
    is_typed_output_runner_function,
    typed_output_stage_erasure_issue_specs,
)

DEFAULT_SOURCE_ROOTS = ("src", "app", "backend", "server", "frontend/src", "packages", "scripts")
PYTHON_SUFFIXES = {".py"}
FRONTEND_SUFFIXES = {".js", ".jsx", ".ts", ".tsx"}
EXCLUDED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
}
GENERATED_FILE_MARKERS = (
    "This file was auto-generated",
    "@generated",
    "auto-generated by",
)
ROUTE_METHODS = {"get", "post", "put", "patch", "delete"}
DEFAULT_ROUTE_PATH_PARTS = {"routers", "routes"}
STATE_MACHINE_FILENAMES = {"state_machine.py", "state_machines.py"}


@dataclass(frozen=True)
class Thresholds:
    python_file_lines: int = 800
    frontend_file_lines: int = 800
    python_function_lines: int = 80
    python_class_public_methods: int = 30
    python_route_count: int = 20


@dataclass(frozen=True)
class PythonMetrics:
    functions: dict[str, int] = field(default_factory=dict)
    classes: dict[str, int] = field(default_factory=dict)
    unowned_dict_returns: set[str] = field(default_factory=set)
    map_any_boundaries: set[str] = field(default_factory=set)
    typed_output_stage_erasure: set[str] = field(default_factory=set)
    legacy_json_type_imports: set[str] = field(default_factory=set)
    disallowed_jsonobject_fields: set[str] = field(default_factory=set)
    store_jsonobject_returns: set[str] = field(default_factory=set)
    route_count: int = 0


@dataclass(frozen=True)
class Snapshot:
    file_lines: dict[str, int] = field(default_factory=dict)
    python: dict[str, PythonMetrics] = field(default_factory=dict)
    state_machine_paths: set[str] = field(default_factory=set)
    missing_transitions: set[tuple[str, str]] = field(default_factory=set)
    legacy_feedback_active_refs: set[str] = field(default_factory=set)


@dataclass(frozen=True)
class GovernanceIssue:
    path: str
    message: str
    blocking: bool


def _git(root: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), "-c", "core.quotePath=false", *args],
        check=False,
        capture_output=True,
        encoding="utf-8",
        errors="ignore",
        text=True,
    )


def _resolve_base_ref(root: Path, requested: str | None) -> str | None:
    if requested:
        return requested
    result = _git(root, ["rev-parse", "--verify", "HEAD"])
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _git_show(root: Path, ref: str, rel_path: str) -> str | None:
    result = _git(root, ["show", f"{ref}:{rel_path}"])
    if result.returncode != 0:
        return None
    return result.stdout


def _is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_PARTS for part in path.parts)


def _relative_path(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def _default_source_roots(root: Path) -> list[str]:
    existing = [source_root for source_root in DEFAULT_SOURCE_ROOTS if (root / source_root).is_dir()]
    return existing or ["."]


def _iter_source_files(root: Path, source_roots: Iterable[str]) -> Iterable[Path]:
    for source_root in source_roots:
        base = root / source_root
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or _is_excluded(path):
                continue
            if path.suffix in PYTHON_SUFFIXES or path.suffix in FRONTEND_SUFFIXES:
                yield path


def _count_lines_text(text: str) -> int:
    if not text:
        return 0
    return len(text.splitlines())


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def _is_generated_text(text: str) -> bool:
    head = "\n".join(text.splitlines()[:10])
    return any(marker in head for marker in GENERATED_FILE_MARKERS)


def _limit_for(path: str, thresholds: Thresholds) -> int | None:
    suffix = Path(path).suffix
    if suffix in PYTHON_SUFFIXES:
        return thresholds.python_file_lines
    if suffix in FRONTEND_SUFFIXES:
        return thresholds.frontend_file_lines
    return None


def _parse_python_text(text: str, filename: str) -> ast.Module | None:
    try:
        return ast.parse(text, filename=filename)
    except SyntaxError:
        return None


def _node_line_count(node: ast.AST) -> int:
    lineno = getattr(node, "lineno", None)
    end_lineno = getattr(node, "end_lineno", None)
    if not isinstance(lineno, int) or not isinstance(end_lineno, int):
        return 0
    return end_lineno - lineno + 1


def _is_route_decorator(decorator: ast.expr) -> bool:
    call = decorator if isinstance(decorator, ast.Call) else None
    func = call.func if call else decorator
    return isinstance(func, ast.Attribute) and func.attr in ROUTE_METHODS


def _is_route_path(rel_path: str, route_path_parts: set[str]) -> bool:
    return any(part in route_path_parts for part in Path(rel_path).parts)


def _public_method_count(node: ast.ClassDef) -> int:
    return sum(isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) and not item.name.startswith("_") for item in node.body)


def _annotation_contains_dict(annotation: ast.expr | None) -> bool:
    if annotation is None:
        return False
    if isinstance(annotation, ast.Name):
        return annotation.id in {"dict", "Dict"}
    if isinstance(annotation, ast.Attribute):
        return annotation.attr in {"dict", "Dict"}
    if isinstance(annotation, ast.Subscript):
        return _annotation_contains_dict(annotation.value) or _annotation_contains_dict(annotation.slice)
    if isinstance(annotation, ast.Tuple):
        return any(_annotation_contains_dict(item) for item in annotation.elts)
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return _annotation_contains_dict(annotation.left) or _annotation_contains_dict(annotation.right)
    return False


def _is_map_name(annotation: ast.expr) -> bool:
    if isinstance(annotation, ast.Name):
        return annotation.id in {"dict", "Dict", "Mapping", "MutableMapping", "DefaultDict"}
    if isinstance(annotation, ast.Attribute):
        return annotation.attr in {"dict", "Dict", "Mapping", "MutableMapping", "DefaultDict"}
    return False


def _is_any_name(annotation: ast.expr) -> bool:
    if isinstance(annotation, ast.Name):
        return annotation.id == "Any"
    if isinstance(annotation, ast.Attribute):
        return annotation.attr == "Any"
    return False


def _annotation_contains_any(annotation: ast.expr | None) -> bool:
    if annotation is None:
        return False
    if isinstance(annotation, ast.Constant) and isinstance(annotation.value, str):
        try:
            parsed_annotation = ast.parse(annotation.value, mode="eval").body
        except SyntaxError:
            return False
        return _annotation_contains_any(parsed_annotation)
    if _is_any_name(annotation):
        return True
    if isinstance(annotation, ast.Subscript):
        return _annotation_contains_any(annotation.value) or _annotation_contains_any(annotation.slice)
    if isinstance(annotation, ast.Tuple):
        return any(_annotation_contains_any(item) for item in annotation.elts)
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return _annotation_contains_any(annotation.left) or _annotation_contains_any(annotation.right)
    return False


def _annotation_slice_items(annotation: ast.expr) -> list[ast.expr]:
    if isinstance(annotation, ast.Tuple):
        return list(annotation.elts)
    return [annotation]


def _annotation_contains_map_any(annotation: ast.expr | None) -> bool:
    if annotation is None:
        return False
    if isinstance(annotation, ast.Constant) and isinstance(annotation.value, str):
        try:
            parsed_annotation = ast.parse(annotation.value, mode="eval").body
        except SyntaxError:
            return False
        return _annotation_contains_map_any(parsed_annotation)
    if isinstance(annotation, ast.Subscript):
        items = _annotation_slice_items(annotation.slice)
        if _is_map_name(annotation.value) and len(items) == 2 and any(_annotation_contains_any(item) for item in items):
            return True
        return _annotation_contains_map_any(annotation.value) or any(_annotation_contains_map_any(item) for item in items)
    if isinstance(annotation, ast.Tuple):
        return any(_annotation_contains_map_any(item) for item in annotation.elts)
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return _annotation_contains_map_any(annotation.left) or _annotation_contains_map_any(annotation.right)
    return False


def _annotation_target_name(target: ast.expr) -> str:
    if isinstance(target, ast.Name):
        return target.id
    if isinstance(target, ast.Attribute):
        owner = _annotation_target_name(target.value)
        return f"{owner}.{target.attr}" if owner else target.attr
    if isinstance(target, ast.Subscript):
        return _annotation_target_name(target.value)
    return "<unknown>"


def _function_arguments(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[ast.arg]:
    args = [*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs]
    if node.args.vararg is not None:
        args.append(node.args.vararg)
    if node.args.kwarg is not None:
        args.append(node.args.kwarg)
    return args


def _is_owned_dict_return(rel_path: str, qualified_name: str) -> bool:
    path = Path(rel_path)
    if "normalizers" in path.parts:
        return True
    if "records" in path.parts and qualified_name.endswith(".to_payload"):
        return True
    boundary_names = {
        "_coerce_payload",
        "_json_object",
        "filtered_mcp_servers",
        "parse_frontmatter_markdown",
    }
    if qualified_name.rsplit(".", 1)[-1] in boundary_names:
        return True
    boundary_suffixes = (
        "_env",
        "_extra_args",
        "_payload",
        "_version_snapshot",
        ".build_env",
        ".claude_env",
        ".file_context",
        ".policy_json",
        ".to_payload",
        ".to_response",
    )
    return qualified_name.endswith(boundary_suffixes)


class _PythonMetricVisitor(ast.NodeVisitor):
    def __init__(self, rel_path: str, route_path_parts: set[str]) -> None:
        self.rel_path = rel_path
        self.route_path_parts = route_path_parts
        self.scope: list[str] = []
        self.functions: dict[str, int] = {}
        self.classes: dict[str, int] = {}
        self.unowned_dict_returns: set[str] = set()
        self.map_any_boundaries: set[str] = set()
        self.typed_output_stage_erasure: set[str] = set()
        self.legacy_json_type_imports: set[str] = set()
        self.disallowed_jsonobject_fields: set[str] = set()
        self.store_jsonobject_returns: set[str] = set()
        self.route_count = 0

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if is_legacy_json_type_import(self.rel_path, node.module, node.level):
            names = ", ".join(alias.name for alias in node.names)
            self.legacy_json_type_imports.add(f"{node.lineno}:{names}")
        self.generic_visit(node)

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        name = ".".join([*self.scope, node.name])
        self.classes[name] = _public_method_count(node)
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._visit_function(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._visit_function(node)

    def _visit_function(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
        name = ".".join([*self.scope, node.name])
        self.functions[name] = _node_line_count(node)
        if _annotation_contains_dict(node.returns) and not _is_owned_dict_return(self.rel_path, name):
            self.unowned_dict_returns.add(name)
        if is_store_path(self.rel_path) and not node.name.startswith("_") and annotation_contains_name(node.returns, "JsonObject"):
            self.store_jsonobject_returns.add(name)
        if _annotation_contains_map_any(node.returns):
            self.map_any_boundaries.add(f"{name}:return")
        if annotation_contains_output_formatter_result_basemodel(node.returns):
            self.typed_output_stage_erasure.add(f"{name}:return:OutputFormatterResult[BaseModel]")
        if is_typed_output_runner_function(self.rel_path, node.name) and annotation_is_bare_basemodel(node.returns):
            self.typed_output_stage_erasure.add(f"{name}:return:BaseModel")
        for arg in _function_arguments(node):
            if _annotation_contains_map_any(arg.annotation):
                self.map_any_boundaries.add(f"{name}:arg:{arg.arg}")
            if arg.arg == "raw_output" and is_typed_output_completion_function(node.name) and annotation_is_base_json_union(arg.annotation):
                self.typed_output_stage_erasure.add(f"{name}:arg:{arg.arg}:BaseModel|JsonObject")
        if _is_route_path(self.rel_path, self.route_path_parts) and any(_is_route_decorator(decorator) for decorator in node.decorator_list):
            self.route_count += 1
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        target_name = _annotation_target_name(node.target)
        if (
            is_records_path(self.rel_path)
            and self.scope
            and annotation_contains_name(node.annotation, "JsonObject")
            and not is_allowed_jsonobject_field(target_name)
        ):
            qualified_name = ".".join([*self.scope, target_name])
            self.disallowed_jsonobject_fields.add(qualified_name)
        if _annotation_contains_map_any(node.annotation) or _annotation_contains_map_any(node.value):
            qualified_name = ".".join([*self.scope, target_name]) if self.scope else target_name
            self.map_any_boundaries.add(f"{qualified_name}:annotation")
        if annotation_contains_output_formatter_result_basemodel(node.annotation):
            qualified_name = ".".join([*self.scope, target_name]) if self.scope else target_name
            self.typed_output_stage_erasure.add(f"{qualified_name}:annotation:OutputFormatterResult[BaseModel]")
        self.generic_visit(node)

    def visit_Assign(self, node: ast.Assign) -> None:
        if _annotation_contains_map_any(node.value):
            for target in node.targets:
                target_name = _annotation_target_name(target)
                qualified_name = ".".join([*self.scope, target_name]) if self.scope else target_name
                self.map_any_boundaries.add(f"{qualified_name}:annotation")
        if self.rel_path == "app/services/agent_job_worker.py" and annotation_contains_name(node.value, "BaseModel"):
            for target in node.targets:
                target_name = _annotation_target_name(target)
                if target_name == "RunProfileJson":
                    self.typed_output_stage_erasure.add(f"{target_name}:alias:BaseModel")
        self.generic_visit(node)


def _python_metrics(rel_path: str, text: str, route_path_parts: set[str]) -> PythonMetrics:
    tree = _parse_python_text(text, rel_path)
    if tree is None:
        return PythonMetrics()
    visitor = _PythonMetricVisitor(rel_path, route_path_parts)
    visitor.visit(tree)
    return PythonMetrics(
        functions=visitor.functions,
        classes=visitor.classes,
        unowned_dict_returns=visitor.unowned_dict_returns,
        map_any_boundaries=visitor.map_any_boundaries,
        typed_output_stage_erasure=visitor.typed_output_stage_erasure,
        legacy_json_type_imports=visitor.legacy_json_type_imports,
        disallowed_jsonobject_fields=visitor.disallowed_jsonobject_fields,
        store_jsonobject_returns=visitor.store_jsonobject_returns,
        route_count=visitor.route_count,
    )


def _dict_string_keys(tree: ast.Module, name: str) -> set[str] | None:
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == name for target in node.targets):
            if isinstance(node.value, ast.Dict):
                return {key.value for key in node.value.keys if isinstance(key, ast.Constant) and isinstance(key.value, str)}
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            if isinstance(node.value, ast.Dict):
                return {key.value for key in node.value.keys if isinstance(key, ast.Constant) and isinstance(key.value, str)}
    return None


def _missing_state_transitions(rel_path: str, text: str) -> set[tuple[str, str]] | None:
    tree = _parse_python_text(text, rel_path)
    if tree is None:
        return None
    known = _dict_string_keys(tree, "_KNOWN_STATES")
    transitions = _dict_string_keys(tree, "_TRANSITIONS")
    if known is None or transitions is None:
        return None
    return {(rel_path, machine) for machine in known - transitions}


def collect_current_snapshot(
    root: Path,
    source_roots: Iterable[str],
    route_path_parts: set[str],
) -> Snapshot:
    file_lines: dict[str, int] = {}
    python: dict[str, PythonMetrics] = {}
    state_machine_paths: set[str] = set()
    missing_transitions: set[tuple[str, str]] = set()
    legacy_feedback_refs: set[str] = set()

    for path in _iter_source_files(root, source_roots):
        rel_path = _relative_path(root, path)
        text = _read_text(path)
        if _is_generated_text(text):
            continue
        file_lines[rel_path] = _count_lines_text(text)
        legacy_feedback_refs.update(legacy_feedback_active_refs(rel_path, text))
        if path.suffix in PYTHON_SUFFIXES:
            python[rel_path] = _python_metrics(rel_path, text, route_path_parts)
            if path.name in STATE_MACHINE_FILENAMES:
                state_missing = _missing_state_transitions(rel_path, text)
                if state_missing is not None:
                    state_machine_paths.add(rel_path)
                    missing_transitions.update(state_missing)

    return Snapshot(
        file_lines=file_lines,
        python=python,
        state_machine_paths=state_machine_paths,
        missing_transitions=missing_transitions,
        legacy_feedback_active_refs=legacy_feedback_refs | legacy_feedback_repo_refs(root),
    )


def collect_base_snapshot(
    root: Path,
    base_ref: str | None,
    current_paths: Iterable[str],
    state_machine_paths: Iterable[str],
    route_path_parts: set[str],
) -> Snapshot:
    if base_ref is None:
        return Snapshot()

    state_paths = set(state_machine_paths)
    file_lines: dict[str, int] = {}
    python: dict[str, PythonMetrics] = {}
    missing_transitions: set[tuple[str, str]] = set()
    legacy_feedback_refs: set[str] = set()
    for rel_path in sorted(current_paths):
        text = _git_show(root, base_ref, rel_path)
        if text is None or _is_generated_text(text):
            continue
        file_lines[rel_path] = _count_lines_text(text)
        legacy_feedback_refs.update(legacy_feedback_active_refs(rel_path, text))
        if Path(rel_path).suffix in PYTHON_SUFFIXES:
            python[rel_path] = _python_metrics(rel_path, text, route_path_parts)

    for rel_path in sorted(state_paths):
        text = _git_show(root, base_ref, rel_path)
        if text is None:
            continue
        state_missing = _missing_state_transitions(rel_path, text)
        if state_missing is not None:
            missing_transitions.update(state_missing)
    legacy_feedback_refs.update(legacy_feedback_repo_refs(root, base_ref))
    return Snapshot(
        file_lines=file_lines,
        python=python,
        state_machine_paths=state_paths,
        missing_transitions=missing_transitions,
        legacy_feedback_active_refs=legacy_feedback_refs,
    )


def _regression_issue(
    *,
    path: str,
    metric: str,
    current: int,
    previous: int | None,
    limit: int,
) -> GovernanceIssue | None:
    if current <= limit:
        return None
    if previous is None:
        return GovernanceIssue(path, f"new {metric}: {current} > {limit}", True)
    if previous <= limit:
        return GovernanceIssue(path, f"{metric} crossed limit: {previous} -> {current} > {limit}", True)
    if current > previous:
        return GovernanceIssue(path, f"existing {metric} grew: {previous} -> {current} > {limit}", True)
    return GovernanceIssue(path, f"existing {metric} not grown: {current} > {limit}", False)


def collect_file_issues(
    current: Snapshot,
    base: Snapshot,
    thresholds: Thresholds,
) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    for rel_path, lines in sorted(current.file_lines.items()):
        limit = _limit_for(rel_path, thresholds)
        if limit is None:
            continue
        issue = _regression_issue(
            path=rel_path,
            metric="oversized file",
            current=lines,
            previous=base.file_lines.get(rel_path),
            limit=limit,
        )
        if issue is not None:
            issues.append(issue)
    return issues


def collect_python_issues(
    current: Snapshot,
    base: Snapshot,
    thresholds: Thresholds,
) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    for rel_path, metrics in sorted(current.python.items()):
        base_metrics = base.python.get(rel_path, PythonMetrics())
        for name, lines in sorted(metrics.functions.items()):
            issue = _regression_issue(
                path=rel_path,
                metric=f"long function {name}",
                current=lines,
                previous=base_metrics.functions.get(name),
                limit=thresholds.python_function_lines,
            )
            if issue is not None:
                issues.append(issue)
        for name, public_methods in sorted(metrics.classes.items()):
            issue = _regression_issue(
                path=rel_path,
                metric=f"large class {name}",
                current=public_methods,
                previous=base_metrics.classes.get(name),
                limit=thresholds.python_class_public_methods,
            )
            if issue is not None:
                issues.append(issue)
        issue = _regression_issue(
            path=rel_path,
            metric="oversized router file",
            current=metrics.route_count,
            previous=base_metrics.route_count,
            limit=thresholds.python_route_count,
        )
        if issue is not None:
            issues.append(issue)
    return issues


def collect_state_machine_issues(current: Snapshot, base: Snapshot) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    new_missing = current.missing_transitions - base.missing_transitions
    existing_missing = current.missing_transitions & base.missing_transitions
    for rel_path, machine in sorted(new_missing):
        issues.append(
            GovernanceIssue(
                rel_path,
                f"new state machine without transitions: {machine}",
                True,
            )
        )
    for rel_path, machine in sorted(existing_missing):
        issues.append(
            GovernanceIssue(
                rel_path,
                f"existing state machine without transitions not increased: {machine}",
                False,
            )
        )
    return issues


def collect_dict_return_issues(current: Snapshot, base: Snapshot) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    for rel_path, metrics in sorted(current.python.items()):
        base_metrics = base.python.get(rel_path, PythonMetrics())
        new_returns = metrics.unowned_dict_returns - base_metrics.unowned_dict_returns
        for name in sorted(new_returns):
            issues.append(
                GovernanceIssue(
                    rel_path,
                    f"new unowned dict return annotation: {name}",
                    True,
                )
            )
    return issues


def collect_map_any_boundary_issues(current: Snapshot, base: Snapshot) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    for rel_path, metrics in sorted(current.python.items()):
        base_metrics = base.python.get(rel_path, PythonMetrics())
        new_boundaries = metrics.map_any_boundaries - base_metrics.map_any_boundaries
        for name in sorted(new_boundaries):
            issues.append(
                GovernanceIssue(
                    rel_path,
                    f"new broad map[Any] type boundary: {name}",
                    True,
                )
            )
    return issues


def collect_legacy_json_type_import_issues(current: Snapshot, base: Snapshot) -> list[GovernanceIssue]:
    return [
        GovernanceIssue(path, message, blocking)
        for path, message, blocking in legacy_json_type_import_issue_specs(
            current.python,
            base.python,
            PythonMetrics(),
        )
    ]


def collect_issues(
    current: Snapshot,
    base: Snapshot,
    thresholds: Thresholds,
) -> list[GovernanceIssue]:
    issues: list[GovernanceIssue] = []
    issues.extend(collect_file_issues(current, base, thresholds))
    issues.extend(collect_python_issues(current, base, thresholds))
    issues.extend(collect_state_machine_issues(current, base))
    issues.extend(collect_dict_return_issues(current, base))
    issues.extend(collect_map_any_boundary_issues(current, base))
    issues.extend(
        GovernanceIssue(path, message, blocking)
        for path, message, blocking in typed_output_stage_erasure_issue_specs(current.python, base.python, PythonMetrics())
    )
    issues.extend(collect_legacy_json_type_import_issues(current, base))
    issues.extend(
        GovernanceIssue(path, message, blocking) for path, message, blocking in jsonobject_boundary_issue_specs(current.python, base.python, PythonMetrics())
    )
    issues.extend(
        GovernanceIssue(path, message, blocking)
        for path, message, blocking in legacy_feedback_active_ref_issue_specs(
            current.legacy_feedback_active_refs,
            base.legacy_feedback_active_refs,
        )
    )
    return sorted(issues, key=lambda issue: (issue.blocking, issue.path, issue.message), reverse=True)


def print_report(issues: list[GovernanceIssue], mode: str, base_ref: str | None) -> None:
    if base_ref is None:
        print("INFO: no git base ref found; treating all current issues as new.")
    else:
        print(f"INFO: comparing governance metrics against {base_ref}.")

    if not issues:
        print("OK: no Codex governance regressions found.")
        return

    for issue in issues:
        if issue.blocking:
            prefix = "FAIL" if mode == "fail" else "WARN"
        else:
            prefix = "BASELINE"
        print(f"{prefix}: {issue.path}: {issue.message}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check Codex governance regressions against a git base ref.")
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Repository root.")
    parser.add_argument("--mode", choices=("warn", "fail"), default="warn")
    parser.add_argument("--base-ref", help="Git ref to compare against. Defaults to HEAD for local runs.")
    parser.add_argument(
        "--source-root",
        action="append",
        dest="source_roots",
        help="Source root to scan. Defaults to existing common source roots.",
    )
    parser.add_argument(
        "--route-path-part",
        action="append",
        dest="route_path_parts",
        help="Path segment treated as a route module directory. Defaults to routers and routes.",
    )
    parser.add_argument("--python-file-lines", type=int, default=800)
    parser.add_argument("--frontend-file-lines", type=int, default=800)
    parser.add_argument("--python-function-lines", type=int, default=80)
    parser.add_argument("--python-class-public-methods", type=int, default=30)
    parser.add_argument("--python-route-count", type=int, default=20)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    root = args.root.resolve()
    source_roots = args.source_roots or _default_source_roots(root)
    route_path_parts = set(args.route_path_parts or DEFAULT_ROUTE_PATH_PARTS)
    thresholds = Thresholds(
        python_file_lines=args.python_file_lines,
        frontend_file_lines=args.frontend_file_lines,
        python_function_lines=args.python_function_lines,
        python_class_public_methods=args.python_class_public_methods,
        python_route_count=args.python_route_count,
    )

    try:
        base_ref = _resolve_base_ref(root, args.base_ref)
        current = collect_current_snapshot(root, source_roots, route_path_parts)
        base = collect_base_snapshot(
            root,
            base_ref,
            current.file_lines,
            current.state_machine_paths,
            route_path_parts,
        )
        issues = collect_issues(current, base, thresholds)
        issues.extend(GovernanceIssue(issue.path, issue.message, issue.blocking) for issue in collect_docs_governance_issues(root, base_ref))
        issues.extend(GovernanceIssue(issue.path, issue.message, True) for issue in collect_orphan_issues(root))
        issues = sorted(issues, key=lambda issue: (not issue.blocking, issue.path, issue.message))
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print_report(issues, args.mode, base_ref)
    if args.mode == "fail" and any(issue.blocking for issue in issues):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
